const mongoose = require('mongoose');

/**
 * One row = "In Program X, Semester N, course CODE is offered (core/option)."
 * This is what the admin edits to control the master 11/12-semester plan.
 * A student's "regular routine" is generated by reading the CurriculumSlots
 * for (student.program, student.currentSemester).
 */
const curriculumSlotSchema = new mongoose.Schema(
  {
    program: { type: String, required: true, enum: ['CSE', 'EEE', 'ETE'] },
    semester: { type: Number, required: true, min: 1, max: 12 },
    courseCode: { type: String, required: true, uppercase: true, trim: true },
    slotType: { type: String, enum: ['CORE', 'OPTION'], default: 'CORE' },
  },
  { timestamps: true }
);

curriculumSlotSchema.index({ program: 1, semester: 1, courseCode: 1 }, { unique: true });

module.exports = mongoose.model('CurriculumSlot', curriculumSlotSchema);
