// Extracted from "Course Catalog - 166 Credits" (CSE program).
// prerequisites use course codes with a space, matching Course.code format.
const C = 'PROGRAM_CORE', O = 'OPTION', UP = 'UNIVERSITY_PROGRAM';

module.exports = [
  // --- Access Academy ---
  { code: 'AA 099', title: 'Academic Reading & Writing', credits: 3, category: 'ACCESS_ACADEMY', prerequisites: [] },
  { code: 'AA 150', title: 'Fundamentals of Quantitative Reasoning', credits: 3, category: 'ACCESS_ACADEMY', prerequisites: [] },
  { code: 'AA 200', title: 'Student Development Seminar', credits: 3, category: 'ACCESS_ACADEMY', prerequisites: [] },

  // --- Language ---
  { code: 'ENG 111', title: 'Advanced Academic Reading & Writing', credits: 3, category: 'LANGUAGE', prerequisites: ['AA 099'] },
  { code: 'ENG 112', title: 'Advanced Academic Listening & Speaking', credits: 1.5, category: 'LANGUAGE', prerequisites: [] },

  // --- University Program (selection) ---
  { code: 'HUM 201', title: 'Macro & Microeconomics', credits: 3, category: UP, prerequisites: [] },
  { code: 'HUM 203', title: 'Communication Skills for Engineers', credits: 3, category: UP, prerequisites: [] },
  { code: 'HUM 211', title: 'Entrepreneurship for Engineers', credits: 3, category: UP, prerequisites: [] },
  { code: 'HUM 301', title: 'Financial & Managerial Accounting', credits: 3, category: UP, prerequisites: [] },
  { code: 'HUM 303', title: 'Sociology & Ethics', credits: 3, category: UP, prerequisites: [] },
  { code: 'HUM 305', title: 'Professional Ethics & Environmental Protection', credits: 3, category: UP, prerequisites: [] },
  { code: 'IPD 400', title: 'Integrated Professional Development', credits: 3, category: UP, prerequisites: [] },
  { code: 'BUS 300', title: 'Business Communication', credits: 3, category: UP, prerequisites: [] },
  { code: 'ECO 203', title: 'Bangladesh Economy', credits: 3, category: UP, prerequisites: [] },
  { code: 'ENG 300', title: 'Critical Reading and Writing Skills', credits: 3, category: UP, prerequisites: [] },
  { code: 'BNG 101', title: 'Bangla Language and Literature', credits: 3, category: UP, prerequisites: [] },
  { code: 'HIS 101', title: 'History of the Emergence of Bangladesh', credits: 3, category: UP, prerequisites: [] },
  { code: 'PSC 100', title: 'Introduction to Political Science', credits: 3, category: UP, prerequisites: [] },
  { code: 'IGLE 300', title: 'International Graduate Leadership Experience', credits: 3, category: UP, prerequisites: [] },
  { code: 'SOC 101', title: 'Introduction to Sociology', credits: 3, category: UP, prerequisites: [] },
  { code: 'JRN 101', title: 'Mass Communication in Contemporary Society', credits: 3, category: UP, prerequisites: [] },
  { code: 'BCH 101', title: 'Bangladesh Culture and Heritage', credits: 3, category: UP, prerequisites: [] },
  { code: 'BPH 101', title: 'Bangladesh Political History', credits: 3, category: UP, prerequisites: [] },
  { code: 'PSY 101', title: 'Principles of Psychology', credits: 3, category: UP, prerequisites: [] },
  { code: 'ANT 101', title: 'Physical Anthropology', credits: 3, category: UP, prerequisites: [] },
  { code: 'FRN 101', title: 'Elementary French I', credits: 3, category: UP, prerequisites: [] },
  { code: 'SDA 101', title: 'Public Speaking', credits: 3, category: UP, prerequisites: [] },
  { code: 'PHI 102', title: 'Moral Problems', credits: 3, category: UP, prerequisites: [] },
  { code: 'PSC 150', title: 'World Politics', credits: 3, category: UP, prerequisites: [] },
  { code: 'IGS 101', title: "Introduction to Gender and Women's Studies", credits: 3, category: UP, prerequisites: [] },
  { code: 'IIR 101', title: 'Introduction to International Relations Theory', credits: 3, category: UP, prerequisites: [] },
  { code: 'WPP 101', title: 'Western Political Philosophy', credits: 3, category: UP, prerequisites: [] },
  { code: 'HUM 105', title: 'Bangladesh Studies', credits: 3, category: UP, prerequisites: [] },
  { code: 'HUM 107', title: 'Industrial Management and Law', credits: 3, category: UP, prerequisites: [] },

  // --- Basic Science ---
  { code: 'PHY 101', title: 'Physics', credits: 3, category: 'BASIC_SCIENCE', prerequisites: [] },
  { code: 'PHY 102', title: 'Physics Laboratory', credits: 1.5, category: 'BASIC_SCIENCE', prerequisites: [], labOf: 'PHY 101', isLab: true },
  { code: 'CHEM 201', title: 'Chemistry', credits: 3, category: 'BASIC_SCIENCE', prerequisites: [] },

  // --- Mathematics ---
  { code: 'MATH 107', title: 'MATH-I: Differential Calculus, Co-ordinate Geometry & Complex Variables', credits: 3, category: 'MATHEMATICS', prerequisites: ['AA 150'] },
  { code: 'MATH 207', title: 'MATH-II: Integral Calculus, Vector Analysis & Linear Algebra', credits: 3, category: 'MATHEMATICS', prerequisites: ['MATH 107'] },
  { code: 'MATH 205', title: 'MATH-III: Numerical Analysis', credits: 3, category: 'MATHEMATICS', prerequisites: ['MATH 107'] },
  { code: 'MATH 203', title: 'MATH-IV: Fourier Analysis, Laplace Transform & Differential Equations', credits: 3, category: 'MATHEMATICS', prerequisites: ['MATH 107'] },
  { code: 'MATH 301', title: 'MATH-V: Probability & Statistics', credits: 3, category: 'MATHEMATICS', prerequisites: ['MATH 107'] },

  // --- Interdisciplinary ---
  { code: 'ME 102', title: 'Engineering Drawing', credits: 1.5, category: 'INTERDISCIPLINARY', prerequisites: [] },
  { code: 'EEE 111', title: 'Introduction to Electrical Engineering', credits: 3, category: 'INTERDISCIPLINARY', prerequisites: [] },
  { code: 'EEE 112', title: 'Introduction to Electrical Engineering Laboratory', credits: 1.5, category: 'INTERDISCIPLINARY', prerequisites: [], labOf: 'EEE 111', isLab: true },
  { code: 'CSE 223', title: 'Digital Electronics & Pulse Technique', credits: 3, category: 'INTERDISCIPLINARY', prerequisites: ['CSE 215'] },
  { code: 'CSE 224', title: 'Digital Electronics & Pulse Technique Laboratory', credits: 1.5, category: 'INTERDISCIPLINARY', prerequisites: [], labOf: 'CSE 223', isLab: true },

  // --- Program Core ---
  { code: 'CSE 111', title: 'Computer Fundamentals and Programming Basics', credits: 3, category: C, prerequisites: [] },
  { code: 'CSE 112', title: 'Computer Fundamentals and Programming Basics Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 111', isLab: true },
  { code: 'CSE 113', title: 'Structured Programming Language', credits: 3, category: C, prerequisites: ['CSE 111'] },
  { code: 'CSE 114', title: 'Structured Programming Language Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 113', isLab: true },
  { code: 'CSE 123', title: 'Object Oriented Programming Language', credits: 3, category: C, prerequisites: ['CSE 113'] },
  { code: 'CSE 124', title: 'Object Oriented Programming Language Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 123', isLab: true },
  { code: 'CSE 115', title: 'Discrete Mathematics', credits: 3, category: C, prerequisites: ['CSE 113'] },
  { code: 'CSE 211', title: 'Data Structure', credits: 3, category: C, prerequisites: ['CSE 113'] },
  { code: 'CSE 212', title: 'Data Structure Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 211', isLab: true },
  { code: 'CSE 215', title: 'Digital Logic Design', credits: 4, category: C, prerequisites: [] },
  { code: 'CSE 216', title: 'Digital Logic Design Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 215', isLab: true },
  { code: 'CSE 221', title: 'Algorithms', credits: 3, category: C, prerequisites: ['CSE 211', 'CSE 123'] },
  { code: 'CSE 222', title: 'Algorithms Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 221', isLab: true },
  { code: 'CSE 225', title: 'Database Management System', credits: 3, category: C, prerequisites: ['CSE 123'] },
  { code: 'CSE 226', title: 'Database Management System Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 225', isLab: true },
  { code: 'CSE 242', title: 'Web Development', credits: 1.5, category: C, prerequisites: ['CSE 225'] },
  { code: 'CSE 311', title: 'Operating System', credits: 3, category: C, prerequisites: ['CSE 123'] },
  { code: 'CSE 312', title: 'Operating System Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 311', isLab: true },
  { code: 'CSE 313', title: 'Data Communication', credits: 3, category: C, prerequisites: [] },
  { code: 'CSE 315', title: 'Microprocessor and Interfacing', credits: 3, category: C, prerequisites: ['CSE 215', 'CSE 113'] },
  { code: 'CSE 316', title: 'Microprocessor and Interfacing Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 315', isLab: true },
  { code: 'CSE 317', title: 'Computer Organization and Architecture', credits: 3, category: C, prerequisites: ['CSE 211', 'CSE 123'] },
  { code: 'CSE 319', title: 'Compiler Design', credits: 3, category: C, prerequisites: ['CSE 123', 'CSE 115', 'CSE 211'] },
  { code: 'CSE 320', title: 'Compiler Design Lab', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 319', isLab: true },
  { code: 'CSE 321', title: 'Computer Graphics', credits: 3, category: C, prerequisites: ['CSE 221'] },
  { code: 'CSE 322', title: 'Computer Graphics Lab', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 321', isLab: true },
  { code: 'CSE 325', title: 'Computer Networks', credits: 3, category: C, prerequisites: ['CSE 313'] },
  { code: 'CSE 326', title: 'Computer Networks Laboratory', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 325', isLab: true },
  { code: 'CSE 327', title: 'Artificial Intelligence', credits: 3, category: C, prerequisites: ['CSE 115', 'CSE 221', 'CSE 315'] },
  { code: 'CSE 328', title: 'Artificial Intelligence Lab', credits: 1.5, category: C, prerequisites: [], labOf: 'CSE 327', isLab: true },
  { code: 'CSE 342', title: 'IoT Based Project Development', credits: 1.5, category: C, prerequisites: ['CSE 315'] },
  { code: 'CSE 411', title: 'Software Engineering', credits: 3, category: C, prerequisites: ['CSE 123', 'CSE 211'] },
  { code: 'CSE 463', title: 'Machine Learning for Big Data Analytics', credits: 3, category: C, prerequisites: ['CSE 225', 'CSE 327'] },
  { code: 'CSE 464', title: 'Python Based Project Development', credits: 1.5, category: C, prerequisites: ['CSE 327'] },
  { code: 'CSE 466', title: 'Mobile App Development', credits: 1.5, category: C, prerequisites: ['CSE 123'] },
  { code: 'CSE 443', title: 'Neural Network and Fuzzy Systems', credits: 3, category: C, prerequisites: ['CSE 327'] },
  { code: 'CSE 400', title: 'Project / Thesis', credits: 6, category: C, prerequisites: ['CSE 315'] },

  // --- Options ---
  { code: 'CSE 301', title: 'Data Warehousing and Mining', credits: 3, category: O, prerequisites: ['CSE 325', 'CSE 311', 'CSE 225'] },
  { code: 'CSE 303', title: 'Introduction to Bioinformatics', credits: 3, category: O, prerequisites: [] },
  { code: 'CSE 307', title: 'Mobile Computing and Applications', credits: 3, category: O, prerequisites: [] },
  { code: 'CSE 308', title: 'Mobile Computing and Applications Lab', credits: 1.5, category: O, prerequisites: [] },
  { code: 'CSE 309', title: 'Distributed Systems', credits: 3, category: O, prerequisites: [] },
  { code: 'CSE 337', title: 'Multimedia Theory', credits: 3, category: O, prerequisites: [] },
  { code: 'CSE 429', title: 'Software Project Management', credits: 3, category: O, prerequisites: ['CSE 225', 'CSE 221'] },
  { code: 'CSE 435', title: 'Pattern Recognition', credits: 3, category: O, prerequisites: [] },
  { code: 'CSE 436', title: 'Pattern Recognition Lab', credits: 1.5, category: O, prerequisites: [], labOf: 'CSE 435', isLab: true },
  { code: 'CSE 439', title: 'Digital Image Processing', credits: 3, category: O, prerequisites: ['CSE 321'] },
  { code: 'CSE 440', title: 'Digital Image Processing Lab', credits: 1.5, category: O, prerequisites: [] },
  { code: 'CSE 447', title: 'Robotics', credits: 3, category: O, prerequisites: [] },
  { code: 'CSE 455', title: 'Business Process Reengineering', credits: 3, category: O, prerequisites: ['CSE 225', 'CSE 327'] },
  { code: 'CSE 457', title: 'Cyber Security', credits: 3, category: O, prerequisites: ['CSE 325'] },
  { code: 'CSE 459', title: 'Network Security', credits: 3, category: O, prerequisites: ['CSE 325'] },
  { code: 'ETE 309', title: 'Digital Signal Processing', credits: 3, category: O, prerequisites: ['CSE 313'] },
  { code: 'ETE 310', title: 'Digital Signal Processing Laboratory', credits: 1.5, category: O, prerequisites: ['CSE 313'] },
  { code: 'ETE 435', title: 'Digital Communication', credits: 3, category: O, prerequisites: ['CSE 313'] },
  { code: 'ETE 436', title: 'Digital Communication Laboratory', credits: 1.5, category: O, prerequisites: ['CSE 313'] },
  { code: 'EEE 213', title: 'Electronics Devices & Circuits', credits: 3, category: O, prerequisites: ['EEE 111'] },
  { code: 'EEE 214', title: 'Electronics Devices & Circuits Lab', credits: 1.5, category: O, prerequisites: [], labOf: 'EEE 213', isLab: true },
  { code: 'EEE 317', title: 'Electrical Drives & Instrumentation', credits: 3, category: O, prerequisites: ['CSE 215', 'EEE 213'] },
  { code: 'EEE 318', title: 'Electrical Drives & Instrumentation Lab', credits: 1.5, category: O, prerequisites: [], labOf: 'EEE 317', isLab: true },
  { code: 'ETE 431', title: 'Mobile Cellular & Wireless Communication', credits: 3, category: O, prerequisites: [] },
];
